---
- name: Installing Apache httpd
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - libselinux-python

- name: Generating httpd.conf file
  template: 
    src=templates/httpd.conf.j2 
    dest=/etc/httpd/conf/httpd.conf

- name: Copy default www (cgi-bin,icons,error,html)
  shell: cp -rL /var/www {{ default_home }}
  sudo: yes
  sudo_user: "{{ default_user }}"

- name: Creating index.html file
  file:
    path={{ default_home }}/www/html/index.html
    state=touch

- name: Generating index.html content
  template:
    src=templates/index.html.j2
    dest={{ default_home }}/www/html/index.html
    owner={{ default_user }} group={{ default_group }}

- name: Copy favicon to document_root
  sudo: yes
  sudo_user: "{{ default_user }}"
  get_url:
    url="https://raw.githubusercontent.com/tlezotte/ansi-rant/master/assets/favicon.ico"
    dest="{{ default_home }}/www/html"
  register: new_archive

- name: Start httpd service
  service: name=httpd state=reloaded enabled=yes