---
# ansible-playbook /vagrant/playbook.yml --connection=local
# create password: python -c 'import crypt; print crypt.crypt("<password>", "<salt>")'
- hosts: all
  sudo: true
  vars:
    server_name: c6.ansi-rant.com
    vagrant_share: /vagrant
    sites_share: /sites
    document_root: /vagrant/somapp/www
    drupal_version: 7.36
    phpmyadmin_version: 4.4.2
    es_version: 1.5.1
    somapp_user: somapp
    somapp_group: somapp
    default_password: vu84dFR1U8cM6
  handlers:
    - name: reload apache
      service: name=httpd state=reloaded
  pre_tasks:
    - include: tasks/required.yml
    - include: tasks/addusers.yml
  tasks:
    - include: tasks/apache.yml
    - include: tasks/php.yml
    - include: tasks/mysql.yml
    - include: tasks/memcached.yml
    - include: tasks/varnish.yml
    - include: tasks/drupal.yml
    - include: tasks/phpmyadmin.yml
    - include: tasks/elasticsearch.yml
  post_tasks:
    - include: tasks/start_services.yml
  
