---
- name: Create default user
  group:
    name={{ default_group }}
    state=present
  
- name: Create default group
  user:
    name={{ default_user }}
    home={{ default_home }}
    shell=/bin/bash
    group={{ default_group }}
    password={{ default_password }}

#- name: Change ownership somapp home
#  file: dest={{ vagrant_share }}/{{ default_user }}
#    owner={{ default_user }}
#    group={{ default_group }}
#    mode=0755 state=directory recurse=yes

- name: Copy default bash_profile
  template:
    src=templates/bash_profile.j2
    dest={{ default_home }}/.bash_profile
    owner={{ default_user }} group={{ default_group }} mode=0755
    