---
- name: Create somapp group
  group: name={{ somapp_group }} state=present
  
- name: Create somapp user
  user: name={{ somapp_user }} home={{ vagrant_share }}/{{ somapp_user }} shell=/bin/bash group={{ somapp_group }} password={{ default_password }}

#- name: Change ownership somapp home
#  file: dest={{ vagrant_share }}/{{ somapp_user }} 
#    owner={{ somapp_user }} 
#    group={{ somapp_group }} 
#    mode=0755 state=directory recurse=yes

#- name: Copy default bash_profile for somapp
#  template: 
#    src=templates/bash_profile.j2 
#    dest={{ vagrant_share }}/{{ somapp_user }}/.bash_profile
#    owner={{ somapp_user }} group={{ somapp_group }} mode=0755
    