---
- name: Installing Apache
  yum:
    name:
      - httpd24
      - httpd24-apr
      - httpd24-apr-util
      - httpd24-httpd
      - httpd24-httpd-tools
      - httpd24-libnghttp2
      - httpd24-mod_ssl
      - httpd24-runtime
    state: latest
  
- name: Generating httpd.conf file
  template: 
    src: "templates/httpd.conf.j2"
    dest: "/etc/httpd/conf/httpd.conf"

- name: Copy default www (cgi-bin,icons,error,html)
  shell: "cp -rL /var/www {{ default_home }}"
  become: yes
  become_user: "{{ default_user }}"

- name: Creating index.html file
  file:
    path: "{{ default_home }}{{ web_home }}/index.html"
    state: touch

- name: Generating index.html content
  template:
    src: "templates/index.html.j2"
    dest: "{{ default_home }}{{ web_home }}/index.html"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"

- name: Creating phpinfo.php file
  file:
    path: "{{ default_home }}{{ web_home }}/phpinfo.php"
    state: touch

- name: Generating phpinfo.php content
  template:
    src: "templates/phpinfo.php.j2"
    dest: "{{ default_home }}{{ web_home }}/phpinfo.php"
    owner: "{{ default_user }} group={{ default_group }}"

- name: Copy favicon to document_root
  become: yes
  become_user: "{{ default_user }}"
  get_url:
    url: "https://raw.githubusercontent.com/tlezotte/ansi-rant/master/assets/favicon.ico"
    dest: "{{ default_home }}{{ web_home }}"
  register: new_archive

- name: Start httpd service
  service: 
    name: httpd
    state: reloaded
