---
- name: Installing Apache httpd
  yum: name=httpd state=present
  
- name: Generating httpd.conf file
  template: 
    src=templates/httpd.conf.j2 
    dest=/etc/httpd/conf/httpd.conf

- name: Copy default www (cgi-bin,icons,error,html)
  copy:
    src=/var/www
    dest={{ document_root }}
    owner={{ default_user }} group={{ default_group }}

- name: Creating index.html file
  file:
    path={{ document_root }}/html/index.html
    state=touch

- name: Generating index.html content
  template:
    src=templates/index.html.j2
    dest={{ document_root }}/html/index.html
    owner={{ default_user }} group={{ default_group }}

- name: Creating phpinfo.php file
  file:
    path={{ document_root }}/html/phpinfo.php
    state=touch

- name: Generating phpinfo.php content
  template:
    src=templates/phpinfo.php.j2
    dest={{ document_root }}/html/phpinfo.php
    owner={{ default_user }} group={{ default_group }}

- name: Start httpd service
  service: name=httpd state=reloaded