---
- name: Installing Apache httpd
  yum: name=httpd state=present
  
- name: Generating httpd.conf file
  template: 
    src=templates/httpd.conf.j2 
    dest=/etc/httpd/conf/httpd.conf

- name: Creating web root
  file: path={{ document_root }} state=directory

- name: Creating index.html file
  file: path={{ document_root }}/index.html state=touch

- name: Generating index.html content
  template:
    src=templates/index.html.j2
    dest={{ document_root }}/index.html

- name: Start httpd service
  service: name=httpd state=reloaded