---
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer
  tags: composer

- name: rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  tags: composer

- name: make composer executable
  file: path=/usr/local/bin/composer mode=a+x state=file
  tags: composer

- name: Install drush with Composer
  shell: /usr/local/bin/composer global require drush/drush:dev-master
  sudo: yes
  sudo_user: "{{ default_user }}"