---
- name: Is Composer Installed
  stat: path={{ root_bin }}/composer
  register: composer
  tags:
    - always

# Update Composer
- name: Update Composer
  shell: "{{ root_bin }}/composer self-update"
  when: composer.stat.exists
  tags:
    - update

# Download Composer installer
- name: Download Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: not composer.stat.exists
  tags:
    - install

# Run Composer installer
- name: Install Composer
  command: php composer-installer.php --install-dir={{ root_bin }} --filename=composer
  args:
    chdir: /tmp
  when: not composer.stat.exists
  tags:
    - install

# Remove Composer installer file
- name: Remove Composer Installer
  file:
    path: /tmp/composer-installer.php
    state: absent
  when: not composer.stat.exists
  tags:
    - install

# Generate composer.json
- name: Generating composer.json file
  template:
    src=composer.json.j2
    dest={{ admin_home }}/.composer/composer.json
  when: composer.stat.exists
  tags:
    - config
