---
- name: Downloading drupal
  shell: /home/vagrant/.composer/vendor/bin/drush dl drupal --drupal-project-rename=drupal --destination={{ default_home }}{{ web_home }}

- name: Create files directory
  file:
    path="{{ default_home }}{{ web_home }}/drupal/sites/default/files"
    state=directory
    owner={{ default_user }} group={{ default_group }}
    mode=0777

- name: Creating settings.php file
  file:
    path="{{ default_home }}{{ web_home }}/drupal/sites/default/settings.php"
    state=touch

- name: Generating settings.php content
  template:
    src=templates/settings.php.j2
    dest="{{ default_home }}{{ web_home }}/drupal/sites/default/settings.php"
    owner={{ default_user }} group={{ default_group }}
    mode=0777

- name: Creating drupal MySQL database
  mysql_db: name=drupal state=present

- name: Creating drupal MySQL username
  mysql_user: name={{ drupal_user }} password={{ default_password_plain }} priv=drupal.*:ALL,GRANT state=present
