---
- name: Downloading drupal
  shell: drush dl drupal --drupal-project-rename=drupal

- name: Create files directory
  file:
    path="{{ document_root }}/drupal-{{ drupal_version }}/sites/default/files"
    state=directory
    owner={{ default_user }} group={{ default_group }}
    mode=0777

- name: Creating settings.php file
  file:
    path="{{ document_root }}/drupal-{{ drupal_version }}/sites/default/settings.php"
    state=touch

- name: Generating settings.php content
  template:
    src=templates/settings.php.j2
    dest="{{ document_root }}/drupal-{{ drupal_version }}/sites/default/settings.php"
    owner={{ default_user }} group={{ default_group }}