---
# TODO: mysql-server isn't installing
- name: install mysql client and server
  yum: name=mysql-server state=present
  yum: name=mysql state=present

- name: Set root password for mysql
  mysql_user: name=root password=vagrant host=localhost
  mysql_user: name={{ default_user }} password={{ default_password_plain }} host=* priv=*.*:ALL,GRANT state=present