---
# TODO: msg: Syntax error on line 292 of /etc/httpd/conf/httpd.conf:
# TODO: DocumentRoot must be a directory
- name: Installing mysql client and server
  yum: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql

- name: Start mysqld service
  service: name=mysqld state=reloaded

- name: Set root password for mysql
  mysql_user: name=root password=vagrant host=localhost
  mysql_user: name={{ default_user }} password={{ default_password_plain }} host=* priv=*.*:ALL,GRANT state=present