---
- name: Installing nginx server
  yum: name=nginx state=present

- name: Generating nginx.conf file
  template:
    src=templates/nginx.conf.j2
    dest=/etc/nginx/nginx.conf

- name: Start nginx service
  service: name=nginx state=reloaded
