---
- name: Installing PHP
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-gd
    - php-ldap
    - php-mbstring
    - php-mysql
    - php-pdo
    - php-pear
    - php-xml
    - php-xmlrpc
    - php-pecl-memcache
    - php-fpm
    - mod-proxy-fcgi

- name: Configuring php.ini file
  template:
    src=templates/php.ini.j2
    dest=/etc/php.ini

- name: Change group owner for PHP session
  file:
    path="/var/lib/php/session"
    group={{ default_group }}

- name: Start php-fpm service
  service: name=php-fpm state=started enabled=yes
