---
- name: Installing PHP
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-gd
    - php-ldap
    - php-mbstring
    - php-mysql
    - php-pdo
    - php-pear
    - php-xml
    - php-xmlrpc
    - php-pecl-memcache
    - php-fpm
