---
- name: Installing PHP 7.3
  yum:
    name:
      - rh-php73
      - rh-php73-php-cli
      - rh-php73-php-common
      - rh-php73-php-devel
      - rh-php73-php-gd
      - rh-php73-php-gmp
      - rh-php73-php-imap
      - rh-php73-php-ldap
      - rh-php73-php-mbstring
      - rh-php73-php-mysqlnd
      - rh-php73-php-odbc
      - rh-php73-php-opcache
      - rh-php73-php-pdo
      - rh-php73-php-pear
      - rh-php73-php-pecl-jsonc
      - rh-php73-php-pecl-jsonc-devel
      - rh-php73-php-pecl-memcache
      - rh-php73-php-process
      - rh-php73-php-soap
      - rh-php73-php-tidy
      - rh-php73-php-xml
      - rh-php73-runtime
      - rh-php73-php-fpm
      - sclo-php73-php-mcrypt
      - libmcrypt
      - ssmtp 
    state: latest

- name: Configuring php.ini file
  template:
    src: "templates/php.ini.j2"
    dest: "/etc/php.ini"

- name: Change group owner for PHP session
  file:
    path: "/var/lib/php/session"
    group: "{{ default_group }}"

- name: Start php-fpm service
  service: 
    name: "php-fpm"
    state: started
    enabled: true
