---
- name: Download php source
  sudo: yes
  #sudo_user: "{{ deploy_user }}"
  get_url:
    url="http://php.net/distributions/php-{{ php_source }}.tar.gz"
    dest="/tmp"
  register: new_archive

- name: Unarchive php source
  sudo: yes
  #sudo_user: "{{ deploy_user }}"
  unarchive:
    src="/tmp/php-{{ php_source }}.tar.gz"
    dest="{{ build_root }}"
    copy=no
  when: new_archive|changed
  
- name: install httpd-devel
  yum: name={{ item }} state=present
  with_items:
    - httpd-devel
    - libxml-devel
    - openssl-devel
    - libcurl-devel
    - libcurl-devel
    - libpng-devel
    - libjpeg-devel
    - freetype-devel
    - libmcrypt-devel
    - readline-devel
    - libtidy-devel
    - libxslt-devel
