---
- name: Download phpMyAdmin
  sudo: yes
  #sudo_user: "{{ deploy_user }}"
  get_url:
    url="https://files.phpmyadmin.net/phpMyAdmin/{{ phpmyadmin_version }}/phpMyAdmin-{{ phpmyadmin_version }}-all-languages.tar.gz"
    dest="/tmp"
  register: new_archive

- name: Unarchive phpMyAdmin
  sudo: yes
  #sudo_user: "{{ deploy_user }}"
  unarchive:
    src="/tmp/phpMyAdmin-{{ phpmyadmin_version }}-all-languages.tar.gz"
    dest={{ default_home }}/www/html
    owner={{ default_user }} group={{ default_group }}
    copy=no
  when: new_archive|changed

- name: Create phpMyAdmin link to version
  file:
    src="{{ default_home }}/www/html/phpMyAdmin-{{ phpmyadmin_version }}-all-languages"
    dest="{{ default_home }}/www/html/phpMyAdmin"
    state=link

- name: Removing phpMyAdmin archive file
  file:
    path="/tmp/phpMyAdmin-{{ phpmyadmin_version }}-all-languages.tar.gz"
    state=absent