---
- name: Download phpMyAdmin
  become: yes
  #become_user: "{{ deploy_user }}"
  get_url:
    url: "https://files.phpmyadmin.net/phpMyAdmin/{{ phpmyadmin_version }}/phpMyAdmin-{{ phpmyadmin_version }}-english.tar.gz"
    dest: "/tmp"
    validate_certs: False
  register: new_archive

- name: Unarchive phpMyAdmin
  become: yes
  #become_user: "{{ deploy_user }}"
  unarchive:
    src: "/tmp/phpMyAdmin-{{ phpmyadmin_version }}-english.tar.gz"
    dest: "{{ default_home }}{{ web_home }}"
    owner: "{{ default_user }} group={{ default_group }}"
    copy: no
  when: new_archive|changed

- name: Create phpMyAdmin link to version
  file:
    src: "{{ default_home }}{{ web_home }}/phpMyAdmin-{{ phpmyadmin_version }}-english"
    dest: "{{ default_home }}{{ web_home }}/phpMyAdmin"
    state: link

- name: Creating config.inc.php file
  file:
    path: "{{ default_home }}{{ web_home }}/phpMyAdmin/config.inc.php"
    state: touch

- name: Generating config.inc.php content
  template:
    src: "templates/config.inc.php.j2"
    dest: "{{ default_home }}{{ web_home }}/phpMyAdmin/config.inc.php"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"

- name: Removing phpMyAdmin archive file
  file:
    path: "/tmp/phpMyAdmin-{{ phpmyadmin_version }}-english.tar.gz"
    state: absent