---
- name: Installing required packages
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - libselinux-python
    - ansible
    - MySQL-python

- name: Generating Ansible hosts file
  template:
    src=templates/ansible_hosts.j2
    dest=/etc/ansible/hosts