---
- name: Stop firewall (iptables) service
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - iptables
    - ip6tables

- name: Installing required packages
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - libselinux-python
    - ansible
    - MySQL-python

- name: Generating Ansible hosts file
  template:
    src=templates/ansible_hosts.j2
    dest=/etc/ansible/hosts

- name: Generating bash_profile file
  template:
    src=templates/bash_profile.j2
    dest={{ vagrant_home }}/.bash_profile
    owner={{ default_user }} group={{ default_group }}

- name: Remove default localtime file
  file:
    path="/etc/localtime"
    state=absent

- name: Link to localtime file
  file:
    src="/usr/share/zoneinfo/{{ timezone }}"
    dest="/etc/localtime"
    state=link

- name: Create software directory
  file:
    path="{{ default_home }}"
    state=directory
    owner={{ default_user }} group={{ default_group }}
    mode=0777