---
#- name: Stop firewall (iptables) service
#  service: name={{ item }} state=stopped enabled=no
#  with_items:
#    - iptables
#    - ip6tables

- name: Disable SELinux
  selinux:
    state: disabled

- name: Get variables related to RHEL Subscriptions
  include_vars:
    file: "~/.ansi-rant/subscription.yml"
  when: ansible_distribution == 'Red Hat Enterprise Linux'

- name: Subscribe to software repositories
  redhat_subscription:
    state: present
    username: "{{ sub_username }}"
    password: "{{ sub_password }}"
    autosubscribe: true
  when: ansible_distribution == 'Red Hat Enterprise Linux'

- name: Installing required packages
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - ansible
    - sqlite
    - python
    - MySQL-python
    - libselinux-python
    - libyaml
    - {{ java_package }}
    - {{ java_package}}_devel

- name: Generating Ansible hosts file
  template:
    src: "templates/ansible_hosts.j2"
    dest: "/etc/ansible/hosts"

- name: Generating bash_profile file
  template:
    src: "templates/bash_profile.j2"
    dest: "{{ vagrant_home }}/.bash_profile"
    owner: "{{ vagrant_user }}"
    group: "{{ vagrant_group }}"

- name: Remove default localtime file
  file:
    path: "/etc/localtime"
    state: absent

- name: Link to localtime file
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: "/etc/localtime"
    state: link