---
- name: Stop firewall (iptables) service
  service: name={{ item }} state=stopped enabled=no
  - iptables
  - ip6tables

- name: Installing required packages
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - libselinux-python
    - ansible
    - MySQL-python

- name: Generating Ansible hosts file
  template:
    src=templates/ansible_hosts.j2
    dest=/etc/ansible/hosts

- name: Generating bash_profile file
  template:
    src=templates/bash_profile.j2
    dest=/home/vagrant/.bash_profile
    owner={{ default_user }} group={{ default_group }}