---
- name: Installing PHP
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-gd
    - php-ldap
    - php-mbstring
    - php-mysql
    - php-pdo
    - php-pear
    - php-xml
    - php-xmlrpc
    - php-pecl-memcache
    - php-fpm

- name: Configuring php.ini file
  template:
    src=templates/php.ini.j2
    dest=/etc/php.ini

- name: Change group owner for PHP session
  file:
    path="/var/lib/php/session"
    group={{ default_group }}

- name: Creating phpinfo.php file
  file:
    path={{ default_home }}/www/html/phpinfo.php
    state=touch

- name: Generating phpinfo.php content
  template:
    src=templates/phpinfo.php.j2
    dest={{ default_home }}/www/html/phpinfo.php
    owner={{ default_user }} group={{ default_group }}